
###normal
POST http://localhost:5000/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=corner578&uip=192.168.1.20&appid=a379ed35-a8e0-48c1-bfce-dc5eed92239c

###wrong user
POST http://localhost:5000/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=unknown.user@gmail.com&passwd=corner578&uip=192.168.1.20&appid=a379ed35-a8e0-48c1-bfce-dc5eed92239c

###wrong password
POST http://localhost:5000/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=wrongpasswd&uip=192.168.1.20&appid=a379ed35-a8e0-48c1-bfce-dc5eed92239c

###wrong appid
POST http://localhost:5000/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=corner578&uip=192.168.1.20&appid=wrong-application-id


###wrong IP
POST http://localhost:5000/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=corner578&appid=a379ed35-a8e0-48c1-bfce-dc5eed92239c