###normal
POST http://accounts.bwretail.com/renew HTTP/1.1
content-type: application/x-www-form-urlencoded

refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbG0iOnsiQXBwSUQiOiJhMzc5ZWQzNS1hOGUwLTQ4YzEtYmZjZS1kYzVlZWQ5MjIzOWMiLCJBc3NlcnQiOnsiYWNjb3VudCI6IioiLCJyb2xlIjoiYWRtaW4ifX0sImVtbCI6Im9sZWcubmFnb3JuaWpAZ21haWwuY29tIiwiZXhwIjoxNTY3Njk0ODI0LCJqdGkiOiIzODM5MzkzOC0zMTY0LTQ3MzItYWQzNy0zNTYxMzQyZDM0MzMiLCJ1aWQiOiI4OTk4MWQ3Mi03NWE0LTQzMjgtOTI0MC04ZDQ4NmI4ZjFjZDciLCJ1aXAiOiIxOTIuMTY4LjEuMjAifQ.WJoKwm2Orb6PAZKaODyH9MzGgIqwtEcVf4zFXHc94i4

###wrong
POST http://accounts.bwretail.com/renew HTTP/1.1
content-type: application/x-www-form-urlencoded

refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbG0iOnsiQXBwSUQiOiJhMzc5ZWQzNS1hOGUwLTQ4YzEtYmZjZS1kYzVlZWQ5MjIzOWMiLCJBc3NlcnQiOnsiYWNjb3VudCI6IioiLCJyb2xlIjoiYWRtaW4ifX0sImVtbCI6Im9sZWcubmFnb3JuaWpAZ21haWwuY29tIiwiZXhwIjoxNTY3Njk0ODI0LCJqdGkiOiIzODM5MzkzOC0zMTY0LTQ3MzItYWQzNy0zNTYxMzQyZDM0MzMiLCJ1aWQiOiI4OTk4MWQ3Mi03NWE0LTQzMjgtOTI0MC04ZDQ4NmI4ZjFjZDciLCJ1aXAiOiIxOTIuMTY4LjEuMjAifQ.WJoKwm2Orb6PAZKaODyH9MzGgIqwtEcVf4zFXHc94i5