
###normal
POST http://localhost/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=corner578

###wrong user
POST http://localhost/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=unknown.user@gmail.com&passwd=corner578

###wrong password
POST http://localhost/authorize HTTP/1.1
content-type: application/x-www-form-urlencoded

email=oleg.nagornij@gmail.com&passwd=wrongpasswd
